spring:
  profiles:
    active: local
---
spring:
  application:
    name: sp-filter-redis
---
spring:
  config:
    activate:
      on-profile: local
  redis:
    principal-session:
      host: localhost
      port: 6379
    principal-migration-status:
      host: localhost
      port: 6379
